[package]
name = "memweb-service"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "libmemwebservice"

[dependencies]
errno = "0.2.8"
libc = "0.2.139"
tokio = "1.25.0"
tokio-tungstenite = "0.18.0"
